url: 'http://izumi-lab.github.io'
title: 'Plham documentation'

include: ['tutorial', 'class']

markdown: kramdown

kramdown:
  input: GFM

highlighter: none

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      math: true
